all:
	h5cc rgrcvr.c readconfig.c  -o rgrcvr -I/usr/local/include/digital_rf -I/home/ubuntu/projects/TangerineSDR-pi/includes -I/usr/local/include/json-c -lconfig  -l:libhdf5.so -ldigital_rf -lpthread -lm -lfftw3 -lfftw3f
